name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ARM toolchain and make
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make

      - name: Build firmware (RED board)
        run: |
          make -C movement/make COLOR=RED

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sensorwatch-firmware
          path: |
            movement/make/build/**/*.uf2
            movement/make/build/**/*.bin
            movement/make/build/**/*.elf
          if-no-files-found: error
